<?php
class booking_tour
{
    public $id,$tour_id,$name_tour,$name_customer,$phone,$email,$city,$country,$departure_day,$adults,$children_6_11,$children_5,$request,$status,$created;
    public function booking_tour($data=array())
    {
    $this->id=isset($data['id'])?$data['id']:'';
    $this->tour_id=isset($data['tour_id'])?$data['tour_id']:'';
    $this->name_tour=isset($data['name_tour'])?$data['name_tour']:'';
    $this->name_customer=isset($data['name_customer'])?$data['name_customer']:'';
    $this->phone=isset($data['phone'])?$data['phone']:'';
    $this->email=isset($data['email'])?$data['email']:'';
    $this->city=isset($data['city'])?$data['city']:'';
    $this->country=isset($data['country'])?$data['country']:'';
    $this->departure_day=isset($data['departure_day'])?$data['departure_day']:'';
    $this->adults=isset($data['adults'])?$data['adults']:'';
    $this->children_6_11=isset($data['children_6_11'])?$data['children_6_11']:'';
    $this->children_5=isset($data['children_5'])?$data['children_5']:'';
    $this->request=isset($data['request'])?$data['request']:'';
    $this->status=isset($data['status'])?$data['status']:'';
    $this->created=isset($data['created'])?$data['created']:'';
          $this->encode();
    }
    public function encode()
        {
            $this->id=addslashes($this->id);
            $this->tour_id=addslashes($this->tour_id);
            $this->name_tour=addslashes($this->name_tour);
            $this->name_customer=addslashes($this->name_customer);
            $this->phone=addslashes($this->phone);
            $this->email=addslashes($this->email);
            $this->city=addslashes($this->city);
            $this->country=addslashes($this->country);
            $this->departure_day=addslashes($this->departure_day);
            $this->adults=addslashes($this->adults);
            $this->children_6_11=addslashes($this->children_6_11);
            $this->children_5=addslashes($this->children_5);
            $this->request=addslashes($this->request);
            $this->status=addslashes($this->status);
            $this->created=addslashes($this->created);
        }
    public function decode()
        {
            $this->id=stripslashes($this->id);
            $this->tour_id=stripslashes($this->tour_id);
            $this->name_tour=stripslashes($this->name_tour);
            $this->name_customer=stripslashes($this->name_customer);
            $this->phone=stripslashes($this->phone);
            $this->email=stripslashes($this->email);
            $this->city=stripslashes($this->city);
            $this->country=stripslashes($this->country);
            $this->departure_day=stripslashes($this->departure_day);
            $this->adults=stripslashes($this->adults);
            $this->children_6_11=stripslashes($this->children_6_11);
            $this->children_5=stripslashes($this->children_5);
            $this->request=stripslashes($this->request);
            $this->status=stripslashes($this->status);
            $this->created=stripslashes($this->created);
        }
}
