<?php
class info
{
    public $id,$id_lang,$about_us,$title_about,$keyword_about,$description_about,$why_us,$title_why,$keyword_why,$description_why,$our_services,$title_services,$keyword_services,$description_services,$terms_conditions,$title_conditions,$keyword_conditions,$description_conditions,$payment_method,$title_,$keyword_,$description_,$privacy_policy,$title_policy,$keyword_policy,$description_policy;
    public function info($data=array())
    {
    $this->id=isset($data['id'])?$data['id']:'';
    $this->id_lang=isset($data['id_lang'])?$data['id_lang']:'';
    $this->about_us=isset($data['about_us'])?$data['about_us']:'';
    $this->title_about=isset($data['title_about'])?$data['title_about']:'';
    $this->keyword_about=isset($data['keyword_about'])?$data['keyword_about']:'';
    $this->description_about=isset($data['description_about'])?$data['description_about']:'';
    $this->why_us=isset($data['why_us'])?$data['why_us']:'';
    $this->title_why=isset($data['title_why'])?$data['title_why']:'';
    $this->keyword_why=isset($data['keyword_why'])?$data['keyword_why']:'';
    $this->description_why=isset($data['description_why'])?$data['description_why']:'';
    $this->our_services=isset($data['our_services'])?$data['our_services']:'';
    $this->title_services=isset($data['title_services'])?$data['title_services']:'';
    $this->keyword_services=isset($data['keyword_services'])?$data['keyword_services']:'';
    $this->description_services=isset($data['description_services'])?$data['description_services']:'';
    $this->terms_conditions=isset($data['terms_conditions'])?$data['terms_conditions']:'';
    $this->title_conditions=isset($data['title_conditions'])?$data['title_conditions']:'';
    $this->keyword_conditions=isset($data['keyword_conditions'])?$data['keyword_conditions']:'';
    $this->description_conditions=isset($data['description_conditions'])?$data['description_conditions']:'';
    $this->payment_method=isset($data['payment_method'])?$data['payment_method']:'';
    $this->title_=isset($data['title_'])?$data['title_']:'';
    $this->keyword_=isset($data['keyword_'])?$data['keyword_']:'';
    $this->description_=isset($data['description_'])?$data['description_']:'';
    $this->privacy_policy=isset($data['privacy_policy'])?$data['privacy_policy']:'';
    $this->title_policy=isset($data['title_policy'])?$data['title_policy']:'';
    $this->keyword_policy=isset($data['keyword_policy'])?$data['keyword_policy']:'';
    $this->description_policy=isset($data['description_policy'])?$data['description_policy']:'';
          $this->encode();
    }
    public function encode()
        {
            $this->id=addslashes($this->id);
            $this->id_lang=addslashes($this->id_lang);
            $this->about_us=addslashes($this->about_us);
            $this->title_about=addslashes($this->title_about);
            $this->keyword_about=addslashes($this->keyword_about);
            $this->description_about=addslashes($this->description_about);
            $this->why_us=addslashes($this->why_us);
            $this->title_why=addslashes($this->title_why);
            $this->keyword_why=addslashes($this->keyword_why);
            $this->description_why=addslashes($this->description_why);
            $this->our_services=addslashes($this->our_services);
            $this->title_services=addslashes($this->title_services);
            $this->keyword_services=addslashes($this->keyword_services);
            $this->description_services=addslashes($this->description_services);
            $this->terms_conditions=addslashes($this->terms_conditions);
            $this->title_conditions=addslashes($this->title_conditions);
            $this->keyword_conditions=addslashes($this->keyword_conditions);
            $this->description_conditions=addslashes($this->description_conditions);
            $this->payment_method=addslashes($this->payment_method);
            $this->title_=addslashes($this->title_);
            $this->keyword_=addslashes($this->keyword_);
            $this->description_=addslashes($this->description_);
            $this->privacy_policy=addslashes($this->privacy_policy);
            $this->title_policy=addslashes($this->title_policy);
            $this->keyword_policy=addslashes($this->keyword_policy);
            $this->description_policy=addslashes($this->description_policy);
        }
    public function decode()
        {
            $this->id=stripslashes($this->id);
            $this->id_lang=stripslashes($this->id_lang);
            $this->about_us=stripslashes($this->about_us);
            $this->title_about=stripslashes($this->title_about);
            $this->keyword_about=stripslashes($this->keyword_about);
            $this->description_about=stripslashes($this->description_about);
            $this->why_us=stripslashes($this->why_us);
            $this->title_why=stripslashes($this->title_why);
            $this->keyword_why=stripslashes($this->keyword_why);
            $this->description_why=stripslashes($this->description_why);
            $this->our_services=stripslashes($this->our_services);
            $this->title_services=stripslashes($this->title_services);
            $this->keyword_services=stripslashes($this->keyword_services);
            $this->description_services=stripslashes($this->description_services);
            $this->terms_conditions=stripslashes($this->terms_conditions);
            $this->title_conditions=stripslashes($this->title_conditions);
            $this->keyword_conditions=stripslashes($this->keyword_conditions);
            $this->description_conditions=stripslashes($this->description_conditions);
            $this->payment_method=stripslashes($this->payment_method);
            $this->title_=stripslashes($this->title_);
            $this->keyword_=stripslashes($this->keyword_);
            $this->description_=stripslashes($this->description_);
            $this->privacy_policy=stripslashes($this->privacy_policy);
            $this->title_policy=stripslashes($this->title_policy);
            $this->keyword_policy=stripslashes($this->keyword_policy);
            $this->description_policy=stripslashes($this->description_policy);
        }
}
